"use client";
import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/index.module.scss";
import Header from "@/components/header";
import Sidepane from "@/components/sidepane";
import IntiativeEntriesList from "@/components/initiativeEntriesList";

export default function Home() {
  const [deleteModeActive, setDeleteModeActive] = useState<boolean>(false);

  function handleDeleteSwitch(val: boolean) {
    setDeleteModeActive(val);
  }

  return (
    <>
      <Head>
        <title>CountMeIn - RPG initiative tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.pageBox}>
        <div className={styles.appBoundingBox}>
          <div className={styles.scrollables}>
            <Header></Header>
            {/* <div className={styles.entryContainer}> */}
            <IntiativeEntriesList
              sessionId={0}
              deleteModeActive={deleteModeActive}
            ></IntiativeEntriesList>
            {/* </div> */}
          </div>
        </div>
        <Sidepane
          deleteModeActive={deleteModeActive}
          handleDeleteSwitch={handleDeleteSwitch}
        ></Sidepane>
      </div>
    </>
  );
}
