import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/index.module.scss";
import Header from "@/components/header";
import Sidepane from "@/components/sidepane";
import IntiativeEntriesList from "@/components/initiativeEntriesList";
import useWindowSize from "@/components/useWindowSize";

export default function Home() {
  const [deleteModeActive, setDeleteModeActive] = useState<boolean>(false);
  const [shouldAdvanceInit, setShouldAdvanceInit] = useState<boolean>(false);
  const screenWidth = useWindowSize().width;
  function isMobile() {
    if (screenWidth) {
      return screenWidth < 780;
    }
    return false;
  }

  function handleDeleteSwitch(val: boolean) {
    setDeleteModeActive(val);
  }

  function setNextTurn() {
    console.log("zoven next turn" + shouldAdvanceInit);
    if (!shouldAdvanceInit) setShouldAdvanceInit(true);
  }
  function turnChangeDone() {
    console.log("botun reset");
    if (shouldAdvanceInit) setShouldAdvanceInit(false);
  }

  return (
    <>
      <Head>
        <title>CountMeIn - RPG initiative tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={isMobile() ? styles.pageBoxMobile : styles.pageBox}>
        <div className={styles.appBoundingBox}>
          <div
            className={
              isMobile() ? styles.scrollablesMobile : styles.scrollables
            }
          >
            <Header></Header>
            {/* <div className={styles.entryContainer}> */}
            <IntiativeEntriesList
              sessionId={0}
              deleteModeActive={deleteModeActive}
              shouldAdvanceTurn={shouldAdvanceInit}
              turnChangeDone={turnChangeDone}
            ></IntiativeEntriesList>
            {/* </div> */}
          </div>
        </div>
        {
          /* !isMobile() &&  */ <Sidepane
            handleChangeTurn={setNextTurn}
            deleteModeActive={deleteModeActive}
            handleDeleteSwitch={handleDeleteSwitch}
          ></Sidepane>
        }
      </div>
    </>
  );
}
