"use client";
import Head from "next/head";
import styles from "@/styles/Index.module.scss";
import Header from "@/components/header";
import Sidepane from "@/components/sidepane";
import IntiativeEntries from "@/components/initiativeEntries";

export default function Home() {
  return (
    <>
      <Head>
        <title>CountMeIn - RPG initiative tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.pageBox}>
        <div className={styles.appBoundingBox}>
          <div className={styles.scrollables}>
            <Header></Header>
            <div className={styles.entryContainer}>
              <IntiativeEntries></IntiativeEntries>
            </div>
          </div>
        </div>
        <Sidepane></Sidepane>
      </div>
    </>
  );
}
